# Generated by Django 2.2.2 on 2019-06-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='')),
                ('link', models.URLField(default='')),
                ('excerpt', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
